---
title: "Data description practice in R"
author: "Kathleen DeBrota"
date: "February 12, 2019"
output: pdf_document
---

Practice with basic data description in R.
```{r}
library(readr)
ozone <- read_csv("USEPAdata 017.csv", col_types ="ccccinnccccccncnncccccc")

#import the dataset
#the codes there represent the type of data you expect in each of the columns. No spaces between these, but each letter means something else and coresponds to each column in order.
#c is character, i is integer, n is numeric I believe
```
```{r}
nrow(ozone) #gives number of rows
ncol(ozone) #number of columns
#str(ozone) #tells you the class of each column, to be sure it's correctly specified
#view top and bottom of data:
head(ozone)
#tail(ozone)
#alternatively,  you can peek at only a few columns:
#head(ozone[, c(6:7, 10)])
```
Check to make sure the data looks right. 
```{r}
table(ozone$Time.Local)
#for some reason this is not working. Supposed to check the timestamps that are attached to the data. For example, 
library(dplyr)
filter(ozone, Time.Local == "13.14") %>%
  select(State.Name, County.Name,Date.Local, Time.Local, Sample.Measurement)
```
Choose a numeric column and practice mean(), median(), sd(), var(), IQR(), range(), diff(range())
```{r}
mean(ozone$'Observation Count', na.rm=TRUE)
#note, you have to ignore the null values when calculating measurements of centrality. If there are nulls they have to be ignored.
#use the str()value to check if the data is numeric or logical, otherwise it will not calculate a mean (of course)
```
```{r}
median(ozone$'Observation Count', na.rm=TRUE)
sd(ozone$'Observation Count', na.rm=TRUE)
var(ozone$'Observation Count', na.rm=TRUE)
IQR(ozone$'Observation Count', na.rm=TRUE)
range(ozone$'Observation Count', na.rm=TRUE)
diff(range(ozone$'Observation Count', na.rm=TRUE))
```

```{r}
#see how many states are represented in the dataset:
select(ozone, 'State Code') %>% unique %>% nrow
#it looks like there are 54 states represented...which is not good.
unique(ozone$'State Code') #in the example, 'State.Name' was used but this does not exist in this dataset.
```
Validate data with external source.
```{r}
summary(ozone$Sample.Measurement) #again this doesn't exist.??
```
Rank the counties by their ozone levels.
```{r}
ranking <- group_by(ozone, state.name, county code) %>%
  summarize(ozone = mean(sample.measurement)) %>% 
  as.data.frame %>%
  arrange(desc(ozone))
#then,
cbind(head(ranking, 10),
      head(ranking2, 10))
#this SHOULD give a table with colunms 'state name', 'county name', 'ozone', where int the ozone column it's the mean value for that county, and ranked by highest to lowest.
```

